### ISSUE TITLE
Making Google do the hard stuff of finding doctors near you rather than manually typing names and contact number of doctors in each city in a file.

### ISSUE THREAD

**Issue by dhananjay1438** [AJV009/meno_mood_hack#1]
As you wanted to make it easier to contact doctor nearby by with your app why don't you make it easier for you as well by asking Google 'doctors near me' and showing the output to the user. It will me much easier for you to show that to users compared to writing all the names and contact numbers of all the doctors from various cities! And it will be wastage of space as well.

**Comment by AJV009** [comment]
Cool! I didnt think of it before. Well Ill have the changes some time soon!

**Comment by AJV009** [comment]
Fixed!
added
```dart
speakfy(){
    voiceWid.add(blogsnip("Click here to search doctors nearby", "https://www.google.com/maps/search/doctors+nearby"));
```
